name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get release info
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get tarball and calculate SHA256
        run: |
          TARBALL_URL="https://github.com/${{ github.repository }}/archive/refs/tags/${{ steps.get_tag.outputs.TAG }}.tar.gz"
          echo "Downloading tarball from $TARBALL_URL"
          curl -sL "$TARBALL_URL" -o "/tmp/chickenipsum-${{ steps.get_tag.outputs.TAG }}.tar.gz"
          SHA256=$(sha256sum "/tmp/chickenipsum-${{ steps.get_tag.outputs.TAG }}.tar.gz" | awk '{print $1}')
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          echo "Calculated SHA256: $SHA256"